### ISSUE TITLE
Query fails when stationcode is string but represents number

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/it.bz.opendatahub.api.mobility-ninja#12]
See:
https://mobility.api.opendatahub.bz.it/v2/flat/ParkingStation,ParkingSensor/occupied/2010-01-01/2018-01-01?limit=-1&where=scode.eq.103&select=tmeasurements

**Comment by Piiit** [comment]
@bertolla You need to quote it, if you like to have it as string...

https://mobility.api.opendatahub.bz.it/v2/flat/ParkingStation,ParkingSensor/occupied/2010-01-01/2018-01-01?limit=-1&where=scode.eq."103"&select=tmeasurements
