### ISSUE TITLE
Strange response message when doing multiple calls at once

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/it.bz.opendatahub.api.mobility-ninja#20]
Related to https://github.com/noi-techpark/bdp-core/issues/207

**UPDATE 2021-09-29**
- [ ] @rcavaliere  has asked Projektionisten to test the fix and see if the problem is solved (waiting for feedback)

Projektionisten got a strange error message when doing the following requests at once:
- https://mobility.api.opendatahub.bz.it/v2/tree/ParkingStation/*/latest?limit=-1&distinct=true&where=and(savailable.eq.true,sactive.eq.true)
- https://mobility.api.opendatahub.bz.it/v2/flat/EChargingPlug/*/latest?limit=-1&distinct=true&where=and(savailable.eq.true,sactive.eq.true)&select=pcode,smetadata,mvalue
- https://mobility.api.opendatahub.bz.it/v2/flat/EChargingStation/*/latest?limit=-1&distinct=true&where=and(savailable.eq.true,sactive.eq.true,smetadata.accessType.neq."PRIVATE")

> **Problem 3: Datenbankfehler**
Bei der gleichzeitigen Ausführung der Anfragen für ParkingStation, EChargingPlug und EChargingStation wird die Anfrage nach Parkplätzen in seltenen Fällen mit einem Fehler 400 beantwortet (Message: ERROR: each UNION query must have the same number of columns\n Position: 2075).
Das Problem ist in Screenshot Problem 3 - Database Error zu sehen.

![image](https://user-images.githubusercontent.com/3582457/127843677-36bd2ff9-b91c-4e30-a4d8-eb49661f185c.png)

I was not able to reproduce the issue. Maybe this problem already got solved?

Edit: I was able to reproduce it now, it's a bug in ninja which should get addressed soon to avoid problems for all API calls.

**Comment by Piiit** [comment]
@bertolla How do you reproduce it?

**Comment by bertolla** [comment]
I made a simple raw webpage which call the api with javascripts fetch api. If I do it fast multiple times the error comes out quiet fast.
Here is the code:
```
<script type="text/javascript">
function fetchOdh(){
fetch("https://mobility.api.opendatahub.bz.it/v2/tree/ParkingStation/*/latest?limit=-1&distinct=true&where=and(savailable.eq.true,sactive.eq.true)").then(data=>data.json());
fetch("https://mobility.api.opendatahub.bz.it/v2/flat/EChargingPlug/*/latest?limit=-1&distinct=true&where=and(savailable.eq.true,sactive.eq.true)&select=pcode,smetadata,mvalue").then(data=>data.json());
fetch("https://mobility.api.opendatahub.bz.it/v2/flat/EChargingStation/*/latest?limit=-1&distinct=true&where=and(savailable.eq.true,sactive.eq.true,smetadata.accessType.neq."PRIVATE")").then(data=>data.json());
}
</script>
<html>
<button onclick="fetchOdh()">Hello world</button>
</html>
```

**Comment by bertolla** [comment]
Sorry, had the wrong quotes on the last fetch. Should be working now

**Comment by Piiit** [comment]
@bertolla So it does work, or is the bug still there? What should be working now?

**Comment by Piiit** [comment]
Aaa... forget it, you were talking about your test code in the comment above... :-)

**Comment by Piiit** [comment]
https://www.infoq.com/articles/Java-Concurrency-Static-Analysis-with-ThreadSafe/

https://www.yegor256.com/2018/03/27/how-to-test-thread-safety.html
