### ISSUE TITLE
As a Open Data Hub Mobility Data Consumer I would like to get through the Open Data Hub the real-time public transportation data through the GTFS-RT interface provided by STA (implementation of a proxy)

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.api.mobility-ninja#35]
In addition to what already implemented inhttps://github.com/noi-techpark/it.bz.opendatahub.api.mobility-ninja/issues/29 (GTFS data of STA), we should also provide and publish a proxy so to give 3rd parties the link to the GTFS-RT interface, which is currently is https://efa.sta.bz.it/gtfs-r/

This means that we should create a proxy so that Open Data Hub users wanting to access this resource should be pointed to this link through e.g. the end-point https://mobility.api.opendatahub.com/v2/GTFS-RT

Additional notice: the GTFS-RT interface foresees for performance reason that the data are retrieved in the protocol buffer format (check https://developers.google.com/transit/gtfs-realtime), which can not be read with a browser. There is an additional end-point (https://efa.sta.bz.it/gtfs-r/?FORMAT=json) that provides the data as JSON, but mainly to check the content of the interface for a human being. I suggest to consider also this end-point in this "proxy" activity.

**Comment by clezag** [comment]
@rcavaliere  I've added this in testing:

https://mobility.api.opendatahub.testingmachine.eu/v2/GTFS-RT
https://mobility.api.opendatahub.testingmachine.eu/v2/GTFS-RT-JSON

**Comment by rcavaliere** [comment]
Perfect! I think you can put this in production

**Comment by clezag** [comment]
Deployed in production
