### ISSUE TITLE
As an external user of the ODH I would like to get from the API also the geometries of the LinkStations

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.api.mobility-ninja#4]
- [x] Add EDGE API calls
- [x] Extend the tree building mechanism to create JSON tree representations out of EDGE queries
- [x] Generalize tree building to not hardcode tree building mechanisms as it is until now (this will then automatically create trees out of arbitrary complex responses just with some little configuration, but no further programming) --> good for future additions of API calls
- [x] Cache tree building data, to have a better performance
- [x] Update README
- [x] Update api specs
- [x] Use a single coordinate reference system for all responses, that is hardcoded `srid = 4326`
(another user story will be added to use PostGIS functions to generate arbitrary output, like geojson for instance)
 > Moved to #7 
- [x] notify Stefano David to integrate it into the official documentation when done
> Issue = https://github.com/noi-techpark/odh-docs/issues/163

**Comment by Piiit** [comment]
@rcavaliere @bertolla First version done. Please test at https://mobility.api.opendatahub.testingmachine.eu

**Comment by Piiit** [comment]
Now we need to discuss if we need metadata for each station in the edge representation (would add 3 joins), and if we need also parent stations each? However, those additions could reduce performance of the API

**Comment by rcavaliere** [comment]
Nice! Is it possible to have the coordinates in a desired coordinate reference system through a specific API call? For the metadata, I think it is sufficient what the end-point already provides. In case of further requests we can make the API richer and more complex

**Comment by Piiit** [comment]
@rcavaliere That would be possible, but I suggest to open another user story for that, since it is not that trivial to add such non-aggregation functions to the API. Currently, all function automatically trigger a GROUP BY. Another possibility would be to hardcode a desired CRS... What do you think?

**Comment by rcavaliere** [comment]
@Piiit OK, I understand. I agree to create a new user story for that. It should however be clear for a 3rd party, the coordinate reference system in which he gets the geometry. Is there an attribute for that?

**Comment by Piiit** [comment]
@rcavaliere @bertolla Please test 

Swagger = https://swagger.opendatahub.bz.it/?url=https://mobility.api.opendatahub.testingmachine.eu/apispec
API = https://mobility.api.opendatahub.testingmachine.eu

The reference system will be adapted, I start another issue for that.

**Comment by rcavaliere** [comment]
@Piiit @bertolla for me it is OK. In the swagger, I can't do tests since I can't insert values in the required input boxes...

**Comment by Piiit** [comment]
@rcavaliere The swagger has been fixed now

**Comment by rcavaliere** [comment]
@Piiit for me it is fine. If @bertolla has nothing more to comment, we can put this in production.

**Comment by sseppi** [comment]
Since Roberto has tested this issue we can move it on production.
