### ISSUE TITLE
As Italian Ministry of Transportation, I would like South Tyrol to have a SIRI-SX end-point

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.api.mobility-ninja#40]
By the end of September, we need to have such kind of standard interface implemented.
SIRI-SX is the reference service for sharing disruption information in public transport, e.g. journey cancellation.
This interface will be implemented by STA with their suppliers, but are in delay. As MVP of the end-point the proposal is to have something static, related to an end-point controlled by us, which should be https://transmodel.api.opendatahub.com/siri-lite/situation-exchange.
We could then redirect this end-point to the right one, once STA has completed his work.

For the first MVP, the request is to:
- [x] convert the static XML file below as JSON (like other SIRI services)
- [x] let the static JSON file be opened when opening the end-point above

STA will provide the end-point to our temporary URL

- [ ] Remember to close the URL when it is no more necessary.

```
<?xml version="2.0" encoding="UTF-8"?>
<Siri xmlns="http://www.siri.org.uk/siri" xmlns:ns2="http://www.ifopt.org.uk/acsb" xmlns:ns3="http://www.ifopt.org.uk/ifopt" xmlns:ns4="http://datex2.eu/schema/2_0RC1/2_0">
	<ServiceDelivery>
		<ResponseTimestamp>2024-09-06T16:48:38.640+02:00</ResponseTimestamp>
		<ProducerRef>RAP-Alto-Adige</ProducerRef>
		<ResponseMessageIdentifier>1</ResponseMessageIdentifier>
    <SituationExchangeDelivery>
			<ResponseTimestamp>2024-09-06T16:48:38.729+02:00</ResponseTimestamp>
      <SubscriberRef>NAP</SubscriberRef>
			<SubscriptionRef>1</SubscriptionRef>
			<Situations>
				<PtSituationElement>
				</PtSituationElement>
			</Situations>
		</SituationExchangeDelivery>
	</ServiceDelivery>
</Siri>
```

**Comment by clezag** [comment]
@rcavaliere 
I've hosted the JSON file on a S3 bucket, which they can proxy to:
http://sta.siri.mock.s3-website-us-east-1.amazonaws.com/siri-lite-sx.json

Let me know if this can work

**Comment by rcavaliere** [comment]
@clezag perfect! I will ask STA to prepare the end-point and to redirect it to this URL
