### ISSUE TITLE
As a traffic analyst I would like that time series have correct time zones.

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.api.mobility-ninja#5]
It is the bug inside the issue tracker: https://issues.opendatahub.bz.it/Ticket/Display.html?id=710

**Comment by Piiit** [comment]
@rcavaliere This bug has been fixed now. In addition, I have also added a `timezone` parameter, such that a user can set the response time zone at any timezone. This parameter is only available for `latest` and `from-to` history calls...

See https://github.com/noi-techpark/it.bz.opendatahub.api.mobility-ninja/tree/development#time-zones for details.

The bug described above is fixed, the time zones of the time boundaries are kept now as given. Before they have been removed during date range parsing, which was wrong.

The swagger works now also with testingmachine... --> https://https://mobility.api.opendatahub.testingmachine.eu

Please test and see if the response times are correct, and the time range includes only the correct timestamps. @bertolla told me that on the database we have only UTC, and that the writer or datacollector handles time transformation accordingly.

**Comment by Piiit** [comment]
@rcavaliere Can you please write to CISMA and maybe also ask for beta testing?

**Comment by rcavaliere** [comment]
@Piiit I asked CISMA via the Issue Tracker to test this. Once we get a feedback we can close this issue and put the new API version in production

**Comment by rcavaliere** [comment]
CISMA has tested it and it works as expected. Please put this in production!

**Comment by Piiit** [comment]
@rcavaliere Done
