### ISSUE TITLE
As a consumer of the API geometries I want to have always the same reference system

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.api.mobility-ninja#7]
See #4 

I will for now just hardcode the same reference system as it is already set for station coordinates.

We need to decide what we want and eventually open other user stories for that. Configurable reference systems or select functions (postgis functions) to translate to any ref. system maybe?

**Comment by Piiit** [comment]
@rcavaliere @bertolla 
Edge geometries are now exposed as geojson in srid 4326. This ref.sys. is hardcoded for now. 

Testable with http://localhost:8081/tree,edge/*?select=egeometry,secoordinate&where=ecode.eq.%2240%22

The old coordinates are not represented as geojson, however we could maybe add a flag to the api to transform them into a geojson as well. What do you think?

**Comment by rcavaliere** [comment]
@Piiit I agree

**Comment by Piiit** [comment]
@rcavaliere I will create a new geojson parameter user story, so we can close this one
