### ISSUE TITLE
As Mobility API v2 consumer, I do not want to see data that has been marked as not available

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.api.mobility-ninja#8]
- [x] the available fields should still be visible in ninja for select and where clauses (we do not want to break the API specs)
- [x] add a standard where clause to all queries in ninja that filters all non-true available station (null or false)
- [x] add some test cases to the dirtylittlehelpers comparison script
- [x] update the README

Before going live!
- [x] open a user story for RTD to update the "available vs active" description and give a hint that we no longer expose unavailable stations

Questions for @rcavaliere:
- [x] Should available = null stations be visible or hidden? Should we add a constraint that the available field must be non-null?
> we hide all stations that have available = null, we do not add a constraint to the writer for that
- [x] What if a parent is not available, but the station itself is?
> we hide stations if the parent is not available (this holds only if the parent is part of the query, if we select only stations alone this check cannot be made)

**Comment by Piiit** [comment]
@rcavaliere Should available = null fields be visible or hidden?

**Comment by rcavaliere** [comment]
If available = NULL hidden, also the parent stations associated

**Comment by Piiit** [comment]
@rcavaliere OK, I will do that now... unfortunately, our test-server is currently down... so I cannot show you the new API for testing. We will fix that tomorrow

**Comment by Piiit** [comment]
Related to https://github.com/noi-techpark/infrastructure/issues/14

**Comment by rcavaliere** [comment]
Did you already implement this in the production environment? In the analytics dashboard I already see only LinkStations that are available!

**Comment by Piiit** [comment]
No, maybe the filter has been set inside the webapp?

**Comment by rcavaliere** [comment]
Probably, I was thinking the same...

**Comment by Piiit** [comment]
@rcavaliere please test 

Example calls: Should return an empty response...
https://mobility.api.opendatahub.testingmachine.eu/v2/flat,edge/*?where=or(seavailable.neq.true,sbavailable.neq.true,eavailable.neq.true)

https://mobility.api.opendatahub.testingmachine.eu/v2/tree,edge/*?where=or(seavailable.neq.true,sbavailable.neq.true,eavailable.neq.true)

https://mobility.api.opendatahub.testingmachine.eu/v2/flat,node/*?where=savailable.neq.true

...should return data: telling that we have only true values
https://mobility.api.opendatahub.testingmachine.eu/v2/flat,node/*?select=savailable&limit=-1

**Comment by rcavaliere** [comment]
@Piiit I receive no data also with the last call... is that the desired behaviour?

**Comment by Piiit** [comment]
Response of the last call should be:

```
{
  "offset": 0,
  "data": [
    {
      "savailable": true
    }
  ],
  "limit": -1
}
```

It is possible that you executed the calls during my last deployment of a new version... please try again

**Comment by rcavaliere** [comment]
Ah OK, if so it's OK

**Comment by Piiit** [comment]
I will put it in production then

**Comment by Piiit** [comment]
@rcavaliere @ohnewein 
We will deploy also version 1.0.0, which brings a huge performance improvement compared to the actual version 0.9.0... however, we need to upgrade the server first. See https://github.com/noi-techpark/infrastructure/issues/14
